steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}', '.' ]
    id: 'build'
    waitFor: ['-']
    env:
      - 'DOCKER_BUILDKIT=1'

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}' ]
    id: 'push-image'
    waitFor: ['build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--set-env-vars=FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET},NODE_ENV=${_NODE_ENV}'
      - '--cpu=1'
      - '--memory=2Gi'
    id: 'deploy'
    waitFor: ['push-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['image', 'prune', '-f']
    

timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY

