name: Deploy to Google Cloud Run using Cloud Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - run: |
        sudo apt-get install python2.7
        export CLOUDSDK_PYTHON="/usr/bin/python2"

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with gcloud
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > temp_key.json
        gcloud auth activate-service-account --key-file=temp_key.json
        rm temp_key.json


    - name: Set gcloud project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker image using Cloud Build and push to GCR
      run: gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/ytdl-dev:latest

    - name: Deploy to Google Cloud Run
      run: gcloud run deploy yt-downloader --image gcr.io/$GCP_PROJECT_ID/ytdl-dev:latest --region us-central1 --platform managed --allow-unauthenticated
